### ISSUE TITLE
Don't install on Hassio (x86)

### ISSUE THREAD

**Issue by vincegre** [kdw2060/hassio-addons#28]
Hi

I added the github in repository list and when I try to install the calendar integration I get that error:

![2022-10-16 17 44 28 n6i71nveptxx72q10614vld17u87jnhh ui nabu casa 3051ce691ffd](https://user-images.githubusercontent.com/3164888/196044708-1dfb5837-4f4d-4d5e-8246-0ee18f2a0b92.png)

I'm running Hassio on x86 platform  (latest version: 

Home Assistant 2022.10.4
Supervisor 2022.10.0
Operating System 9.2
Interface utilisateur : 20221010.0 - latest

Thanks

Vincèn

**Comment by kdw2060** [comment]
hi, haven't tried to reproduce this yet, so don't know if it's an issue that all new installs have.
Previously when a similar thing happened it was because Home Assistant devs had made some changes to the technical setup of add-ons and add-ons needed to be changed accordingly. 
I have looked at the developers blog they maintain, but couldn´t immediately find a recent change that looks like it would have an impact here. Could also be because of some change in [s6](https://github.com/just-containers/s6-overlay), which is what HA uses for container (add-on) images.

If you were to find some info in a thread about some other add-on or about some other s6 container where a similar issue occurred that would help to point me in the right direction.

**Comment by kdw2060** [comment]
I cannot reproduce this issue. 
I have clarified the installation instructions and made adding the repo easier.
A lot has been changed in the code for version 0.300 so maybe that fixes this issue you have to in some way.
